package com.leko.kvm

/**
 * A set of JVM access and property flags, stored as the raw `access_flags`
 * bitmask from the class file format (JVMS §4.1, §4.5, §4.6).
 *
 * Each element kind has its own flag type because the same bit means different
 * things depending on context. For example, `0x0020` is `ACC_SUPER` on a class
 * but `ACC_SYNCHRONIZED` on a method.
 *
 * @see ClassFlags
 * @see MethodFlags
 * @see FieldFlags
 */
sealed interface AccessFlags {
    /** The raw bitmask, exactly as stored in the class file. */
    val bits: Int
}

/**
 * Access flags of a class, interface, enum or annotation (JVMS Table 4.1-B).
 *
 * Instances are created through the constants in the [companion object][Companion]
 * and combined with [plus]. The constructor is `internal`.
 *
 * Flag combinations are built with [plus]. Queries use the `is*` properties
 * and the [has], [hasAny] and [hasAll] functions.
 */
@JvmInline
value class ClassFlags internal constructor(override val bits: Int) : AccessFlags {
    /** `ACC_PUBLIC`: declared public, so it may be accessed from outside its package. */
    val isPublic      get() = bits and 0x0001 != 0

    /** `ACC_PROTECTED`: declared protected. Only meaningful for nested classes (`InnerClasses` attribute). */
    val isProtected   get() = bits and 0x0004 != 0

    /** `ACC_FINAL`: declared final, so it cannot be subclassed. */
    val isFinal       get() = bits and 0x0010 != 0

    /** `ACC_SUPER`: treat `invokespecial` superclass calls specially. Always set in modern class files. */
    val isSuper       get() = bits and 0x0020 != 0  // always set in modern JVM

    /** `ACC_INTERFACE`: this is an interface, not a class. */
    val isInterface   get() = bits and 0x0200 != 0

    /** `ACC_ABSTRACT`: declared abstract, so it must not be instantiated. */
    val isAbstract    get() = bits and 0x0400 != 0

    /** `ACC_SYNTHETIC`: generated by the compiler and not present in source code. */
    val isSynthetic   get() = bits and 0x1000 != 0

    /** `ACC_ANNOTATION`: declared as an annotation interface. */
    val isAnnotation  get() = bits and 0x2000 != 0

    /** `ACC_ENUM`: declared as an enum class. */
    val isEnum        get() = bits and 0x4000 != 0

    /** Returns the union of this flag set and [other] (bitwise OR). */
    operator fun plus(other: ClassFlags) = ClassFlags(bits or other.bits)

    /** Returns the union of this flag set and the raw bitmask [other] (bitwise OR). */
    operator fun plus(other: Int): ClassFlags = ClassFlags(bits or other)

    /** Compares the raw bitmasks numerically. This is not a subset or superset relation. */
    operator fun compareTo(other: ClassFlags) = bits.compareTo(other.bits)

    /** Compares the raw bitmask numerically against [other]. */
    operator fun compareTo(other: Int) = bits.compareTo(other)

    /**
     * Returns the flags present in both this set and [other] (bitwise AND).
     *
     * Note that the result is a [ClassFlags], not a [Boolean]. Use [hasAny]
     * to test whether the sets overlap.
     */
    infix fun intersects(other: ClassFlags) = ClassFlags(bits and other.bits)

    /** Returns the flags present in both this set and the raw bitmask [other] (bitwise AND). */
    infix fun intersects(other: Int) = ClassFlags(bits and other)

    /** Returns `true` if every bit of [flag] is set in this set. */
    infix fun has(flag: ClassFlags): Boolean = (bits and flag.bits) == flag.bits

    /** Returns `true` if at least one bit of [mask] is set in this set. */
    infix fun hasAny(mask: ClassFlags): Boolean = (bits and mask.bits) != 0

    /** Returns `true` if every bit of [mask] is set in this set. Equivalent to [has]. */
    infix fun hasAll(mask: ClassFlags): Boolean = (bits and mask.bits) == mask.bits


    companion object {
        /** No flags set except `ACC_SUPER`, which is always set in modern class files. */
        val EMPTY       = ClassFlags(0x0020)  // ACC_SUPER always set

        /** `ACC_PUBLIC` (`0x0001`). */
        val PUBLIC      = ClassFlags(0x0001)

        /** `ACC_PROTECTED` (`0x0004`). */
        val PROTECTED   = ClassFlags(0x0004)

        /** `ACC_FINAL` (`0x0010`). */
        val FINAL       = ClassFlags(0x0010)

        /** `ACC_INTERFACE` (`0x0200`). */
        val INTERFACE   = ClassFlags(0x0200)

        /** `ACC_ABSTRACT` (`0x0400`). */
        val ABSTRACT    = ClassFlags(0x0400)

        /** `ACC_SYNTHETIC` (`0x1000`). */
        val SYNTHETIC   = ClassFlags(0x1000)

        /** `ACC_ANNOTATION` (`0x2000`). */
        val ANNOTATION  = ClassFlags(0x2000)

        /** `ACC_ENUM` (`0x4000`). */
        val ENUM        = ClassFlags(0x4000)

        /** Mask of flags that identify the kind of class: [INTERFACE] and [ANNOTATION]. */
        val CLASS_SPECIFIC = INTERFACE + ANNOTATION

        /** Mask of the visibility flags: [PUBLIC] and [PROTECTED]. */
        val VISIBILITY = PUBLIC + PROTECTED
    }
}

/**
 * Access flags of a method (JVMS Table 4.6-A).
 *
 * Instances are created through the constants in the [companion object][Companion]
 * and combined with [plus]. The constructor is `internal`.
 */
@JvmInline
value class MethodFlags internal constructor(override val bits: Int) : AccessFlags {
    /** `ACC_PUBLIC`: declared public. */
    val isPublic        get() = bits and 0x0001 != 0

    /** `ACC_PRIVATE`: declared private, so it is accessible only within the defining class. */
    val isPrivate       get() = bits and 0x0002 != 0

    /** `ACC_PROTECTED`: declared protected. */
    val isProtected     get() = bits and 0x0004 != 0

    /** `ACC_STATIC`: declared static. */
    val isStatic        get() = bits and 0x0008 != 0

    /** `ACC_FINAL`: declared final, so it must not be overridden. */
    val isFinal         get() = bits and 0x0010 != 0

    /** `ACC_SYNCHRONIZED`: invocation is wrapped by a monitor use. */
    val isSynchronized  get() = bits and 0x0020 != 0

    /** `ACC_BRIDGE`: a bridge method generated by the compiler (for example for generics or covariant returns). */
    val isBridge        get() = bits and 0x0040 != 0

    /** `ACC_VARARGS`: declared with a variable number of arguments. */
    val isVarargs       get() = bits and 0x0080 != 0

    /** `ACC_NATIVE`: declared native, so it is implemented in a language other than Java. */
    val isNative        get() = bits and 0x0100 != 0

    /** `ACC_ABSTRACT`: declared abstract, so it has no implementation. */
    val isAbstract      get() = bits and 0x0400 != 0

    /** `ACC_SYNTHETIC`: generated by the compiler and not present in source code. */
    val isSynthetic     get() = bits and 0x1000 != 0

    /** Returns the union of this flag set and [other] (bitwise OR). */
    operator fun plus(other: MethodFlags) = MethodFlags(bits or other.bits)

    /** Returns the union of this flag set and the raw bitmask [other] (bitwise OR). */
    operator fun plus(other: Int): MethodFlags = MethodFlags(bits or other)

    /** Compares the raw bitmasks numerically. This is not a subset or superset relation. */
    operator fun compareTo(other: MethodFlags) = bits.compareTo(other.bits)

    /** Compares the raw bitmask numerically against [other]. */
    operator fun compareTo(other: Int) = bits.compareTo(other)

    /**
     * Returns the flags present in both this set and [other] (bitwise AND).
     *
     * Note that the result is a [MethodFlags], not a [Boolean]. Use [hasAny]
     * to test whether the sets overlap.
     */
    infix fun intersects(other: MethodFlags) = MethodFlags(bits and other.bits)

    /** Returns the flags present in both this set and the raw bitmask [other] (bitwise AND). */
    infix fun intersects(other: Int) = MethodFlags(bits and other)

    /** Returns `true` if every bit of [flag] is set in this set. */
    infix fun has(flag: MethodFlags): Boolean = (bits and flag.bits) == flag.bits

    /** Returns `true` if at least one bit of [mask] is set in this set. */
    infix fun hasAny(mask: MethodFlags): Boolean = (bits and mask.bits) != 0

    /** Returns `true` if every bit of [mask] is set in this set. Equivalent to [has]. */
    infix fun hasAll(mask: MethodFlags): Boolean = (bits and mask.bits) == mask.bits


    companion object {
        /** No flags set. */
        val EMPTY        = MethodFlags(0)

        /** `ACC_PUBLIC` (`0x0001`). */
        val PUBLIC       = MethodFlags(0x0001)

        /** `ACC_PRIVATE` (`0x0002`). */
        val PRIVATE      = MethodFlags(0x0002)

        /** `ACC_PROTECTED` (`0x0004`). */
        val PROTECTED    = MethodFlags(0x0004)

        /** `ACC_STATIC` (`0x0008`). */
        val STATIC       = MethodFlags(0x0008)

        /** `ACC_FINAL` (`0x0010`). */
        val FINAL        = MethodFlags(0x0010)

        /** `ACC_SYNCHRONIZED` (`0x0020`). */
        val SYNCHRONIZED = MethodFlags(0x0020)

        /** `ACC_BRIDGE` (`0x0040`). */
        val BRIDGE       = MethodFlags(0x0040)

        /** `ACC_VARARGS` (`0x0080`). */
        val VARARGS      = MethodFlags(0x0080)

        /** `ACC_NATIVE` (`0x0100`). */
        val NATIVE       = MethodFlags(0x0100)

        /** `ACC_ABSTRACT` (`0x0400`). */
        val ABSTRACT     = MethodFlags(0x0400)

        /** `ACC_SYNTHETIC` (`0x1000`). */
        val SYNTHETIC    = MethodFlags(0x1000)

        /**
         * Mask of flags that describe how a method is implemented or invoked, as
         * opposed to its visibility or modifiers shared with other elements:
         * [SYNCHRONIZED], [BRIDGE], [VARARGS], [NATIVE] and [ABSTRACT].
         */
        val METHOD_SPECIFIC = SYNCHRONIZED + BRIDGE + VARARGS + NATIVE + ABSTRACT

        /** Mask of the visibility flags: [PUBLIC], [PRIVATE] and [PROTECTED]. */
        val VISIBILITY = PUBLIC + PRIVATE + PROTECTED
    }
}

/**
 * Access flags of a field (JVMS Table 4.5-A).
 *
 * Instances are created through the constants in the [companion object][Companion]
 * and combined with [plus]. The constructor is `internal`.
 */
@JvmInline
value class FieldFlags internal constructor(override val bits: Int) : AccessFlags {
    /** `ACC_PUBLIC`: declared public. */
    val isPublic     get() = bits and 0x0001 != 0

    /** `ACC_PRIVATE`: declared private. */
    val isPrivate    get() = bits and 0x0002 != 0

    /** `ACC_PROTECTED`: declared protected. */
    val isProtected  get() = bits and 0x0004 != 0

    /** `ACC_STATIC`: declared static. */
    val isStatic     get() = bits and 0x0008 != 0

    /** `ACC_FINAL`: declared final, so it must not be assigned after construction. */
    val isFinal      get() = bits and 0x0010 != 0

    /** `ACC_VOLATILE`: declared volatile, so it cannot be cached. */
    val isVolatile   get() = bits and 0x0040 != 0

    /** `ACC_TRANSIENT`: declared transient, so it is skipped by persistent object managers. */
    val isTransient  get() = bits and 0x0080 != 0

    /** `ACC_SYNTHETIC`: generated by the compiler and not present in source code. */
    val isSynthetic  get() = bits and 0x1000 != 0

    /** `ACC_ENUM`: declared as an element of an enum class. */
    val isEnum       get() = bits and 0x4000 != 0

    /** Returns the union of this flag set and [other] (bitwise OR). */
    operator fun plus(other: FieldFlags) = FieldFlags(bits or other.bits)

    /** Returns the union of this flag set and the raw bitmask [other] (bitwise OR). */
    operator fun plus(other: Int): FieldFlags = FieldFlags(bits or other)

    /** Compares the raw bitmasks numerically. This is not a subset or superset relation. */
    operator fun compareTo(other: FieldFlags) = bits.compareTo(other.bits)

    /** Compares the raw bitmask numerically against [other]. */
    operator fun compareTo(other: Int) = bits.compareTo(other)

    /**
     * Returns the flags present in both this set and [other] (bitwise AND).
     *
     * Note that the result is a [FieldFlags], not a [Boolean]. Use [hasAny]
     * to test whether the sets overlap.
     */
    infix fun intersects(other: FieldFlags) = FieldFlags(bits and other.bits)

    /** Returns the flags present in both this set and the raw bitmask [other] (bitwise AND). */
    infix fun intersects(other: Int) = FieldFlags(bits and other)

    /** Returns `true` if every bit of [flag] is set in this set. */
    infix fun has(flag: FieldFlags): Boolean = (bits and flag.bits) == flag.bits

    /** Returns `true` if at least one bit of [mask] is set in this set. */
    infix fun hasAny(mask: FieldFlags): Boolean = (bits and mask.bits) != 0

    /** Returns `true` if every bit of [mask] is set in this set. Equivalent to [has]. */
    infix fun hasAll(mask: FieldFlags): Boolean = (bits and mask.bits) == mask.bits


    companion object {
        /** No flags set. */
        val EMPTY      = FieldFlags(0)

        /** `ACC_PUBLIC` (`0x0001`). */
        val PUBLIC     = FieldFlags(0x0001)

        /** `ACC_PRIVATE` (`0x0002`). */
        val PRIVATE    = FieldFlags(0x0002)

        /** `ACC_PROTECTED` (`0x0004`). */
        val PROTECTED  = FieldFlags(0x0004)

        /** `ACC_STATIC` (`0x0008`). */
        val STATIC     = FieldFlags(0x0008)

        /** `ACC_FINAL` (`0x0010`). */
        val FINAL      = FieldFlags(0x0010)

        /** `ACC_VOLATILE` (`0x0040`). */
        val VOLATILE   = FieldFlags(0x0040)

        /** `ACC_TRANSIENT` (`0x0080`). */
        val TRANSIENT  = FieldFlags(0x0080)

        /** `ACC_SYNTHETIC` (`0x1000`). */
        val SYNTHETIC  = FieldFlags(0x1000)

        /** `ACC_ENUM` (`0x4000`). */
        val ENUM       = FieldFlags(0x4000)

        /** Mask of flags specific to fields: [VOLATILE] and [TRANSIENT]. */
        val FIELD_SPECIFIC = VOLATILE + TRANSIENT

        /** Mask of the visibility flags: [PUBLIC], [PRIVATE] and [PROTECTED]. */
        val VISIBILITY = PUBLIC + PRIVATE + PROTECTED
    }
}