package com.leko.kvm.bytecode

import com.leko.kvm.ConcreteClass
import com.leko.kvm.MethodBody
import com.leko.kvm.typing.ClassType


/**
 * Generates JVM class-file bytes for this class.
 *
 * @param generator the bytecode generator used for the conversion.
 * Defaults to the suitable default [defaultGenerator].
 * @return the generated class-file bytes.
 */
fun ConcreteClass.bytes(generator: BytecodeGenerator = defaultGenerator()): ByteArray =
    generator.generate(this)

/**
 * Converts this JVM bytecode tree into a method body.
 *
 * The tree is traversed using an [InstructionGenerator], producing the
 * corresponding JVM instructions and exception-handler entries.
 *
 * When [autoTerminate] is enabled, a void return instruction is appended
 * if the generated instruction sequence does not already end in a return
 * or throw instruction.
 *
 * @param autoTerminate whether to automatically append a void return when
 * the generated body has no terminating return or throw instruction.
 * Defaults to `true`.
 * @return the resulting method body.
 */
fun JBCTree.toMethodBody(autoTerminate: Boolean = true): MethodBody {
    val instructions = mutableListOf<Instruction>()
    val exceptionHandlers = mutableListOf<ExceptionHandler>()

    class Generator: InstructionGenerator {
        override fun emit(instruction: Instruction) {
            instructions.add(instruction)
        }
        override fun placeLabel(label: Label) {
            instructions.add(LabelInstruction(label))
        }
        override fun registerExceptionHandler(start: Label, end: Label, handler: Label, type: ClassType?) {
            exceptionHandlers.add(ExceptionHandler(start, end, handler, type))
        }
    }

    this.generate(Generator())
    if (autoTerminate) {
        val lastInst = instructions.lastOrNull()
        if (lastInst !is ReturnInstruction && lastInst !is AThrowInstruction) {
            instructions.add(VReturnInstruction)
        }
    }
    return MethodBody(instructions, exceptionHandlers)
}

/**
 * Converts every instruction in this list to its human-readable
 * representation.
 *
 * This is primarily useful for debugging, diagnostics, and displaying
 * generated bytecode.
 *
 * @return the readable representation of each instruction in the same order.
 */
fun List<Instruction>.readable(): List<String> = map { it.readable() }
